----CUSTOMER-----
ALTER TABLE DIM_CUSTOMER
DROP PRIMARY KEY CASCADE;
DROP TABLE DIM_CUSTOMER CASCADE CONSTRAINTS;

CREATE TABLE DIM_CUSTOMER
(
  CUST_CODE         VARCHAR2(10 BYTE)           NOT NULL,
  CUST_NAME         VARCHAR2(25 BYTE),
  CUST_ADDRESS      VARCHAR2(50 BYTE),
  CUST_STATENAME    VARCHAR2(20 BYTE),
  CUST_COUNTRYNAME  VARCHAR2(20 BYTE),
  CUST_CONTACT      VARCHAR2(20 BYTE),
  CUST_TYPE         VARCHAR2(20 BYTE),
  ENTRY_DATE        DATE,
  UPDATE_DATE       DATE,
  CURR_FLAG         INTEGER,
  CUST_KEY          INTEGER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE UNIQUE INDEX DIM_CUSTOMER_PK ON DIM_CUSTOMER
(CUST_KEY)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DIM_CUSTOMER ADD (
  CONSTRAINT DIM_CUSTOMER_PK
 PRIMARY KEY
 (CUST_KEY)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
---------LOCATION----------------------

ALTER TABLE DIM_LOCATION
DROP PRIMARY KEY CASCADE;
DROP TABLE DIM_LOCATION CASCADE CONSTRAINTS;

CREATE TABLE DIM_LOCATION
(
  LOCATION_KEY          NUMBER(10),
  LOCATION_CODE         VARCHAR2(10 BYTE)       NOT NULL,
  LOCATION_NAME         VARCHAR2(50 BYTE),
  LOCATION_STATENAME    VARCHAR2(50 BYTE),
  LOCATION_COUNTRYNAME  VARCHAR2(50 BYTE),
  LOCENTRY_DATE         DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE UNIQUE INDEX DIM_LOCATION_PK ON DIM_LOCATION
(LOCATION_KEY)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DIM_LOCATION ADD (
  CONSTRAINT DIM_LOCATION_PK
 PRIMARY KEY
 (LOCATION_KEY)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

----------PRODUCT----------

ALTER TABLE DIM_PRODUCT
DROP PRIMARY KEY CASCADE;
DROP TABLE DIM_PRODUCT CASCADE CONSTRAINTS;

CREATE TABLE DIM_PRODUCT
(
  PRODUCT_KEY        NUMBER(10),
  PRODUCT_CODE       VARCHAR2(10 BYTE)          NOT NULL,
  PRODUCT_NAME       VARCHAR2(50 BYTE),
  PRODUCT_DESC       VARCHAR2(100 BYTE),
  PRODUCT_BRAND      VARCHAR2(50 BYTE),
  PRODUCTENTRY_DATE  DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE UNIQUE INDEX DIM_PRODUCT_PK ON DIM_PRODUCT
(PRODUCT_KEY)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DIM_PRODUCT ADD (
  CONSTRAINT DIM_PRODUCT_PK
 PRIMARY KEY
 (PRODUCT_KEY)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

---------STORE-------

ALTER TABLE DIM_STORE
DROP PRIMARY KEY CASCADE;
DROP TABLE DIM_STORE CASCADE CONSTRAINTS;

CREATE TABLE DIM_STORE
(
  STORE_KEY        NUMBER(10),
  STORE_CODE       VARCHAR2(10 BYTE)            NOT NULL,
  STORE_NAME       VARCHAR2(50 BYTE),
  STORE_ADDRESS    VARCHAR2(200 BYTE),
  STORE_DESC       VARCHAR2(100 BYTE),
  STOREENTRY_DATE  DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE UNIQUE INDEX DIM_STORE_PK ON DIM_STORE
(STORE_KEY)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DIM_STORE ADD (
  CONSTRAINT DIM_STORE_PK
 PRIMARY KEY
 (STORE_KEY)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));

--------TIME----------------
ALTER TABLE DIM_TIME
DROP PRIMARY KEY CASCADE;
DROP TABLE DIM_TIME CASCADE CONSTRAINTS;

CREATE TABLE DIM_TIME
(
  TIME_KEY    NUMBER(10),
  TIME_DAY    NUMBER(10),
  TIME_MONTH  NUMBER(10),
  TIME_YEAR   NUMBER(10),
  TIME_DATE   DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCACHE
NOPARALLEL
NOMONITORING;


CREATE UNIQUE INDEX DIM_TIME_PK ON DIM_TIME
(TIME_KEY)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE DIM_TIME ADD (
  CONSTRAINT DIM_TIME_PK
 PRIMARY KEY
 (TIME_KEY)
    USING INDEX 
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
               ));
